services:
  db:
    image: postgres:15-alpine
    container_name: postgres_tramites
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_tramites
    ports:
      - "5432:5432"
    volumes:
      # Montamos el script SQL para que se ejecute al inicializar
      - ./01init.sql:/docker-entrypoint-initdb.d/01init.sql
      - ./02seed.sql:/docker-entrypoint-initdb.d/02seed.sql
      # Volumen para persistencia de datos (opcional pero recomendado)
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
